/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#303030",
        "primary-container": "#dcd6ff",
        "on-secondary-container": "#3b6e57",
        "outline": "#78767e",
        "surface-container": "#f0eded",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0f0",
        "primary": "#5e5a7d",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#1b1736",
        "secondary-fixed-dim": "#9cd2b7",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#2b1706",
        "tertiary-fixed": "#ffdcc4",
        "tertiary": "#765842",
        "on-surface-variant": "#47464d",
        "outline-variant": "#c9c5ce",
        "on-surface": "#1b1c1c",
        "surface-bright": "#fcf9f8",
        "secondary": "#356851",
        "primary-fixed-dim": "#c8c2ea",
        "on-primary-container": "#5f5c7e",
        "error": "#ba1a1a",
        "on-primary": "#ffffff",
        "surface-variant": "#e4e2e1",
        "on-secondary": "#ffffff",
        "surface-container-high": "#eae7e7",
        "on-tertiary-container": "#785943",
        "secondary-fixed": "#b8efd2",
        "surface-dim": "#dcd9d9",
        "on-primary-fixed-variant": "#464364",
        "on-secondary-fixed": "#002114",
        "surface-tint": "#5e5a7d",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#e4dfff",
        "surface-container-highest": "#e4e2e1",
        "on-tertiary-fixed-variant": "#5c412c",
        "tertiary-fixed-dim": "#e6bfa4",
        "on-background": "#1b1c1c",
        "inverse-primary": "#c8c2ea",
        "surface-container-low": "#f6f3f2",
        "on-secondary-fixed-variant": "#1b503b",
        "surface": "#fcf9f8",
        "on-error": "#ffffff",
        "tertiary-container": "#fcd3b7",
        "background": "#fcf9f8",
        "secondary-container": "#b8efd2"
      },
      borderRadius: {
        DEFAULT: "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "sm": "12px",
        "container-margin": "24px",
        "lg": "24px",
        "xl": "32px",
        "md": "16px",
        "base": "8px",
        "xs": "4px",
        "xxl": "48px"
      },
      fontFamily: {
        "h1": ["Plus Jakarta Sans"],
        "label-md": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "body-md": ["Be Vietnam Pro"],
        "label-sm": ["Be Vietnam Pro"],
        "h3": ["Plus Jakarta Sans"],
        "h2": ["Plus Jakarta Sans"]
      },
      fontSize: {
        "h1": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "label-md": ["14px", { "lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.4", "fontWeight": "500" }],
        "h3": ["20px", { "lineHeight": "1.4", "fontWeight": "700" }],
        "h2": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
